### ISSUE TITLE
[shadenfreude] Roadmap: Minimum Useful Package

### ISSUE THREAD

**Issue by hmans** [hmans/three-vfx#72]
Which nodes (and/or features) does shadenfreude need to reach a "Minimum Useful Package" state?

### Nodes

Value Nodes:

- [x] Float
- [x] Vector2
- [x] Vector3
- [x] ~Color~ It's just a Vector3
- [x] Vector4
- [x] Mat3
- [x] Mat4

Variable Nodes:

- [x] Uniform
- [x] Attribute
- [x] Varying

Input Nodes:

- [x] VertexNormal
- [x] VertexPosition
  - [ ] configurable to different spaces, or with separate output values per space?
- [x] Time
- [x] Texture
- [ ] Texture3D

Math Nodes:

- [x] Operator
- [x] Add
- [x] Subtract
- [x] Multiply
- [x] Divide
- [x] Mix
- [x] Sin
- [x] Cos
- [ ] Tan
- [ ] Blend
- [x] Lerp (== Mix)
- [ ] Inverse Lerp
- [ ] Clamp
- [ ] Saturate (Clamp 0, 1)
- [ ] Min
- [ ] Max
- [ ] OneMinus
- [ ] Fraction
- [ ] Round
- [ ] Truncate
- [ ] Floor
- [ ] Ceil
- [ ] Sign
- [x] Step
- [x] Smoothstep
- [ ] Waves (Sine, Cosine, Triangle, Sawtooth, Square)

Easing:

- [ ] all of them! Aaaaah

Vectors:

- [x] Split
- [x] Join
- [x] Normalize
- [ ] Distance
- [ ] Cross
- [ ] Dot

Noise Nodes:

- [ ] ...?

Effect Nodes:

- [x] Fresnel

Master Nodes:

- [x] CustomShaderMaterialMasterNode (for CustomShaderMaterial)
- [x] ShaderMaterialMasterNode

### Other Stuff

- [x] Maybe remove the type shortcuts `Float`, `Bool` etc. again? They don't communicate well that they represent _values_, but people might think they represent _variables_, considering we have variable creation helpers of the same names.
- [x] Make `Uniform` useful
- [x] ~Remove/rework `only`?~ - nah, it's fine. We will keep iterating on it.
- [x] `title` and `name` -> `name` and `slug`
- [x] ~Maybe rename `inputs` to something like `variables` or `locals`? (They are not inputs, but dependencies!)~ - nah, `inputs` is fine
- [x] Provide a mechanism for injecting functions into the GLSL without causing conflicts
  - [x] Ideally, multiple instances of the same node should only declare the function once (global-scope id generator?)
  - [x] The function name should be dynamically scoped (function name generator?)
- [ ] Provide a good README
- [x] Provide a good starter CSB - https://codesandbox.io/s/github/hmans/shadenfreude-sandbox?file=/src/App.js
- [x] Move this library to its own repository
- [x] Find the final name (or stay with Shadenfreude)

**Comment by hmans** [comment]
Sandbox: https://codesandbox.io/s/github/hmans/shadenfreude-sandbox?file=/src/App.js
